config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/sapphire', as: 'rails_admin'
  # resources :questions
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
 
  root "pages#home"
  get '/scoreboard' => 'pages#scoreboard'
  get '/error' => 'pages#error'
  post '/abdv' => 'pages#abdv'
  
  resources :users, only: [:edit, :update]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= current_user

    if user.admin?
      can :manage, :all
      can :access, :rails_admin
      can :dashboard
    else
  	  can :read, :all
      cannot :access, :rails_admin
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

validates :name, :email, :provider, :uid, :role, presence: true

  	enum role: [
				:normal,
				:admin
               ]

class << self
	$found_or_created=0;
	def create_with_omniauth(auth)
		uid=auth.uid
		info=auth.info.symbolize_keys!
		if User.exists?(uid: uid)
			user=User.find_by(uid: uid)
			$found_or_created=1
		else
			user=User.create(uid: uid)
			user.name=info.name+" "
			user.provider=auth.provider
			user.image_url=info.image
			user.score = 0
			user.email = info.email
			user.role = 0
			$found_or_created=2
		end
		user.save!
		user	
	end

	def f_o_c
		return $found_or_created
	end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user
  helper_method :current_score
  helper_method :authenticate_user!

  rescue_from CanCan::AccessDenied do | exception |
    redirect_to '/error', alert: exception.message
  end


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  private

   def authenticate
     if !current_user
       flash[:error] = "Please Sign In"
       redirect_to root_path
     end
  end



  def current_score
  	if current_user == nil
      @current_score = 0
    else
      @current_score = current_user.score
    end
    @current_score
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :find_question, only: [:home, :abdv]
  before_action :authenticate, only: [:abdv, :scoreboard]
  

  def home
  end

  def abdv
    answer = params[:myAnswer]
    right_answer = @question.answer
   	if answer==right_answer
  		user = current_user
  		user.score = user.score+10
  		user.save!
	  	find_question
      myHash = Hash.new
      if @question == nil
        myHash["Statement"] = "XXX"
        myHash["Score"] = current_score
      else
        myHash["Statement"] = @question.statement
        myHash["Image"] = @question.image_url
        myHash["Score"] = current_score
      end
      myHash = myHash.to_json
  	else
      myHash = Hash.new
      myHash["Score"] = -1;
      myHash = myHash.to_json
    end
      respond_to do |format|
      format.html {}
      format.json { render json: myHash}
    end
  end
  
  def scoreboard
    @users=User.order(updated_at: :desc)
    @users=@users.sort_by(&:score).reverse
  end


  def error
    
  end
  
  private

  def find_question 
    if Question.exists?(id: current_score/10+1)
  	  @question = Question.find(current_score/10+1)
    else
      @question = nil
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base

def create
	auth=request.env["omniauth.auth"]
	user=User.create_with_omniauth(auth)
	session[:user_id]=user.id
	value=User.f_o_c
		if value==2
			flash[:success]="Complete your Profile!!"
  			redirect_to edit_user_path(user)
		else
			flash[:success] = "Successfully logged in"
			redirect_to root_url
		end
end

def destroy
	reset_session
	flash[:success] = "Successfully logged out"
	redirect_to root_url
end

def failure
redirect_to root_url, :alert => "Authentication error"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 

	def edit
		if User.exists?(id: params[:id])
		  @user=User.find(params[:id])
		end

		if @user!=current_user
			redirect('/404.html')
		end
	end

	def update
		@user=User.find(params[:id])
		if @user.update(user_params)
			flash[:notice]="Your Profile was successfully Updated!!"
			redirect_to root_path
		else
			flash[:notice]="Sorry!! Could not save profile!"
			render 'edit'
		end
	end

	private

	def user_params
	  params.require(:user).permit(:name,:college)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TH</title>
  		<meta name="description" content="Learn how to code your first responsive website with the new Twitter Bootstrap 3.">

		<!-- Mobile viewport optimized -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #ecf0f1;">
<% unless flash.empty? %>
     <script type="text/javascript">
          <% flash.each do |f| %>
	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	     	 toastr['<%= type %>']('<%= f[1] %>');
	   <% end %>
     </script>
<% end %>

<div class="navbar navbar-default" id="mera">
<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
 <ul class="nav navbar-nav">

<% if current_user %>
 
<% if current_user.admin? %>
	<li><%= link_to "Admin", '/sapphire' %></li>
	<% end %>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Edit Your Profile", edit_user_path(current_user) %></li>
  <li><%= link_to "Scoreboard", scoreboard_path %></li>
  <%= link_to "Log Out", signout_path, class: "btn btn-default navbar-btn" %>

<% else %>
  <%= link_to "Facebook", '/auth/facebook', class: "btn btn-default navbar-btn" %>
<% end %>

</ul>
</div>
</div>
<div class="container" id="main">
<%= yield %>
</div>

<br><br><br>
<!-- <footer id="neeche">
	<div class="container">
		<div class="row">
			<div class="col-sm-2">
			<h6>Copyright &copy; 2013 {alchemist95}</h6>
			</div>
-
			<div class="col-sm-4">
				<h6>About Us</h6>
				<p>sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!sapphire is bringing it!!</p>
			</div>

			<div class="col-sm-2">
				<h6>Navigation</h6>
				<ul class="unstyled">
					<li><a href="#">Home</a></li>
					<li><a href="#">Services</a></li>
					<li><a href="#">Links</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>

			<div class="col-sm-2">
				<h6>Follow Us</h6>
				<ul class="unstyled">
					<li><a href="#">Twitter</a></li>
					<li><a href="#">Facebook</a></li>
					<li><a href="#">Google Plus</a></li>
				</ul>
			</div>

			<div class="col-sm-2">
				<h6>Coded with <span class="glyphicon glyphicon-heart"></span> by alchemist95</h6>
			</div>					</div>
	</div>

</footer> -->


</body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
<div class="container" id="userPro">
<%= image_tag(current_user.image_url, size: '50x50') %>&nbsp;&nbsp;
<%= current_user.name %><%= ", "%><%= current_user.college %>

<p style="font-size:20px; float:right;"><%= "Score : "%><span id="myScore"><%= current_score %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= "Level : "%><span id="myLevel"><%= (current_score==0)?1:current_score/10+1 %></span></p>


<div id="hunt">
<% if @question!=nil %>
	<div id="myQuestion">
	<h2><%= @question.statement %></h2>
	<span id="myImage"><%= image_tag(@question.image_url)%></span>
	</div>
	<br /><br />


	<form id="answerForm">
	<input type="text" name="answer" id="myAnswerText" placeholder="Type your answer here">
	<input type="submit" name="submit" id="myAnswer">
	</form>
<% else %>
<br /><br />
<h2>Wait for upcoming questions</h2>
<% end %>
</div>


<div id="myResult">
</div>

<% end %>

app/views/pages/scoreboard.html.erb
<br /><br/>
<h2 align="center">Scoreboard</h2>
<hr>

<div class="container">
<div class="row">
<% @users.each do |user| %>

<div class="col-md-2">
<%= image_tag(user.image_url, size: '50x50') %>
</div>
<div class="col-md-4">
<%= user.name %>
</div>
<div class="col-md-2">
<%= user.score %>
</div>
<div class="col-md-4">
<%= user.updated_at.strftime("%v %X") %>
</div>

<br /><br/><hr>
<% end %>
</div>
</div>
<hr>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
<br/>
<div class="container">
	<div class="row">
	<div class="col-md-3">
	</div>
	<div class="col-md-6">

	<div class="panel panel-warning">
    	<div class="panel-heading"><h3 style="text-align: center">Edit Your Profile
 	<span style="float:right"><div class="btn-group"><%= link_to "Back", root_path, class:"btn btn-primary" %><%= f.submit "Update", class: 'btn btn-success' %></span></div></h3>
 	</div>
        <div class="panel-body">
        	<div class="form-group">
        	<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
			</div>
<br />

            <div class="form-group">
            <%= f.label :score %><br />
            <%= @user.score%>
            </div>
            <!-- <div class="form-group">
                <%#= f.label :dob%>
                <div class='input-group date' id='datetimepicker1'>
                   <%#= f.text_field :dob, class: "form-control"%>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div> -->
<br />
            <div class="form-group">
            <%=f.label :college %>
            <%= f.select :college, options_for_select(College.all.collect {|c| c.name.titleize }),{}, class: 'form-control' %>
            </div>
<br />
        </div>
 	</div>
 	</div>

<div class="col-md-3">
	</div>


</div>
</div>

  <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker(
{	format: 'DD/MM/YYYY'}
                	);
            });
        </script>



<% end %>